apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: airline-demo
    newTag: 1.0.0-SNAPSHOT-20230426-193053
    newName: nexus-docker-nexus.apps.cluster-9xv45.9xv45.sandbox2355.opentlc.com/airline-demo
replicas:
  - name: airline-demo
    count: 2